- hosts: webservers
  user: ubuntu
  sudo: True

  vars:
    app_name: DontPanic
    repo_url: https://github.com/dbrenneman/DontPanic.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv/webapps
    wsgi_file: dontpanic.py
    wsgi_callable: app

  tasks:
    - name: ensure log directory
      action: file dest=${webapps_dir}/${app_name}/log state=directory

    - name: deploy code from repository
      action: git repo=$repo_url dest=${webapps_dir}/${app_name}/src remote=$repo_remote version=$repo_version

    - name: install dependencies into virtualenv
      action: pip requirements=${webapps_dir}/${app_name}/src/requirements.txt virtualenv=${webapps_dir}/${app_name}/venv state=present

    - name: create supervisor program config
      action: template src=templates/supervisor.ini dest=/etc/supervisor/${app_name}.ini
      notify:
        - restart app

    - name: create nginx site config
      action: template src=templates/${app_name}.conf dest=/etc/nginx/sites-available/${app_name}.conf

    - name: link nginx config
      action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link
      notify:
        - restart nginx

    - name: start app
      action: shell /usr/local/bin/supervisorctl -c /etc/supervisor/supervisord.conf start ${app_name}

  handlers:
    - name: restart app
      action: shell /usr/local/bin/supervisorctl -c /etc/supervisor/supervisord.conf stop ${app_name}
      action: shell /usr/local/bin/supervisorctl -c /etc/supervisor/supervisord.conf start ${app_name}

    - name: restart nginx
      action: service name=nginx state=restarted