- hosts: webservers
  user: ubuntu
  sudo: True

  vars:
    delete_default_vhost: true
    worker_processes: $ansible_processor_count
    pid: /var/run/nginx.pid

  tasks:

    - name: update apt repository and upgrade outdated packages
      action: apt upgrade=yes update_cache=yes

    - name: install apt packages
      action: apt pkg=$item state=installed
      with_items:
        - python-dev
        - python-setuptools
        - python-imaging
        - git-core
        - nginx

    - name: install pip
      action: easy_install name=pip

    - name: install python libraries
      action: pip name=$item state=present
      with_items:
        - supervisor
        - uwsgi
        - virtualenv

    - name: write nginx.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx

    - name: delete default vhost
      action: file path=/etc/nginx/sites-enabled/default state=absent
      only_if: "$delete_default_vhost"
      notify:
        - restart nginx

    - name: create supervisord configuration directory
      action: file dest=/etc/supervisor state=directory owner=root

    - name: create supervisord configuration file
      action: template src=templates/supervisord.conf dest=/etc/supervisor/supervisord.conf

    - name: create supervisord upstart configuration file
      action: template src=templates/supervisord_upstart.conf dest=/etc/init/supervisord.conf

    - name: create web application directory
      action: file dest=/srv/webapps state=directory

    - name: start supervisord
      action: service name=supervisord state=started enabled=yes

    - name: start nginx
      action: service name=nginx state=started enabled=yes

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted enabled=yes
